#!/usr/bin/env python3
import sys, os
sys.path.append(os.path.dirname(__file__) + '/lib')

import yaml, json
from splunk import Splunk

with open(os.path.dirname(__file__) + '/documentum.yml', 'r') as config_file:
    try:
        config = yaml.safe_load(config_file)
    except yaml.YAMLError as ye:
        print(ye)

def getmodule(block): 
    _component = next(iter(block))
    components = config['components']
    component = components[_component]
    module = component['module']
    if 'splunk' == module:
        splunk = Splunk(component['proto'], component['host'], component['port'])
        splunk.login(component['username'], component['password'])
        return splunk

with open(sys.argv[1], 'r') as md:
    try:
        for line in md:
            if line.startswith('{'):
                block = json.loads(line)
                module = getmodule(block)
                module.process(block)
            else:
                print(line)
    except Error as e:
        print(e)
